CREATE PROCEDURE [dbo].[Lookup_Customer_GetByCustomerId]
	@CustomerId varchar(21)
AS
SET NOCOUNT ON
BEGIN
	SELECT [CUSTOMER_ID]
      ,[CUSTOMER_TYPE]
      ,[CUSTOMER_BRANCH]
      ,[CUSTOMER_BANKER]
      ,[CUSTOMER_STATUS]
      ,[CUSTOMER_SEGMENT]
      ,[BANK_ID]
      ,[CUST_BIRTH_DATE]
      ,[CUSTOMER_LAST_CONTACT]
      ,[CUSTOMER_SGFN]
      ,[CUSTOMER_KUNDENATTRAKT]
      ,[CUSTOMER_BETREUINTENS]
      ,[CUSTOMER_NEXT_CONTACT]
      ,[CUSTOMER_KST]
  FROM [dbo].[CUSTOMERS]
  WHERE [CUSTOMER_ID] = @CustomerId
END
