CREATE TABLE [dbo].[CUSTOMERS](
	[CUSTOMER_ID] [varchar](21) NOT NULL,
	[CUSTOMER_TYPE] [varchar](20) NULL,
	[CUSTOMER_BRANCH] [varchar](6) NULL,
	[CUSTOMER_BANKER] [varchar](16) NULL,
	[CUSTOMER_STATUS] [varchar](5) NULL,
	[CUSTOMER_SEGMENT] [varchar](74) NULL,
	[BANK_ID] [char](5) NULL,
	[CUST_BIRTH_DATE] [date] NULL,
	[CUSTOMER_LAST_CONTACT] [date] NULL,
	[CUSTOMER_SGFN] [varchar](4) NULL,
	[CUSTOMER_KUNDENATTRAKT] [char](35) NULL,
	[CUSTOMER_BETREUINTENS] [char](35) NULL,
	[CUSTOMER_NEXT_CONTACT] [datetime] NULL,
	[CUSTOMER_KST] [varchar](16) NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
))