CREATE TABLE [dbo].[TXN](
	[TXN_ID] [varchar](40) NOT NULL,
	[AGREEMENT_ID] [varchar](21) NOT NULL,
	[CUSTOMER_ID] [varchar](21) NULL,
	[BANK_ID] [char](5) NULL,
	[TXN_CODE] [varchar](11) NULL,
	[TXN_DATE] [date] NULL,
	[TXN_AMOUNT] [numeric](15, 2) NULL,
	[TXN_TEXT] [varchar](200) NULL,
	[CURRENCY_CODE] [varchar](3) NULL,
	[TXN_CUR_AMOUNT] [numeric](15, 2) NULL,
	[TXN_CORR_ACCOUNT] [varchar](40) NULL,
	[TXN_CORR_NAME] [varchar](200) NULL,
	[TXN_CORR_BANK] [varchar](11) NULL,
	[TXN_CORR_COUNTRY] [varchar](2) NULL,
	[CUSTOMER_SEGMENT] [varchar](74) NULL,
	[CUSTOMER_TYPE] [varchar](20) NULL,
	[SALARY_FLAG] [varchar](1) NULL,
	[PRODUCT_ID] [varchar](16) NULL,
 CONSTRAINT [PK_TXN] PRIMARY KEY CLUSTERED ([TXN_ID] ASC))